version: 1
labels:
  - label: "app"
    files:
      - "app/.*"
  - label: "db"
    files:
      - "db/.*"
  - label: "workflows"
    files:
      - '.github/path-filters.yml'
      - '.github/workflows/*'
  - label: "markdown"
    - '**/*.md'