version: 1
labels:
  - label: "app"
    files:
      - "app/.*"
  - label: "db"
    files:
      - "db/.*"
  - label: "workflows"
    files:
      - '.github/*'
      - '.github/workflows/*'
  - label: "markdown"
      - '**/*.md'